---
title: "dynamic_eqtl"
author: "Lifan Liang"
date: "2025-01-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Model formulation

Suppose we have expression data of $n$ samples from $D$ donors. Here a sample could be a single cell, or a meta-cell, or some pseudobulk sample (of many cells) with the same type/state. For each sample, we denote $X_i$ as the context of interest, e.g. treatment, cell state (such as differentiation pseudotime). Additionally, genotype $G_d, 1 \leq d \leq D$ may also affect expression. There is also a possible interaction effect between genotype $G_d$ and the context $X_i$. Our model of gene expression is: 
\begin{equation}
    y_i = \mu + \beta_X X_i + \beta_G G_d + \gamma X_i \cdot G_d + u_d + \epsilon_i,
\end{equation}
where $\beta_X$ and $\beta_G$ are context, and genotype effects, respectively, $\gamma$ is the interaction effect, and $u_d$ is the donor-specific random effect. For simplicity, we do not include some covariates such as sex and age of donors, and percent of mitochondrial reads of cells. 

Fitting the model is computationally expensive. We can rewrite the model to remove the donor random effect. We remove from $y_i$, the average expression of all samples from the donor $d$, $\bar{y}_d$:  
\begin{equation}
    \Delta_i = y_i - \bar{y}_d. 
\end{equation}
Now we can write our model as: 
\begin{equation}
    \Delta_i = \beta_X X_i + \gamma X_i G_d + \epsilon_i = X_i (\beta_X + \gamma G_d) + \epsilon_i. 
\end{equation}
From this model, we can see that the effect of $X_i$ on gene expression depends on the genotype $G_d$, denoted as
\begin{equation}
    \theta_d = \beta_X + \gamma G_d
\end{equation}
This can be viewed as: ``genes modify the environmental effect``. 


## Model fitting

The simplest way to solve the model is a two-step linear regression. We first regress environment $X$ against $\Delta_i$ to estimate the total effect for each donor, $\theta_d$. And the corresponding standard error $\sigma_d$. 

$$
\hat{\theta_d} = (X_d^TX_d)^{-1}X_d^T \Delta_d 
$$

$$
\sigma_d^2 = var(\hat{\theta_d}) = \dfrac{var(Y_d)}{X_d^T X_d}
$$

where $X_d$ is the environment variable in the treatment effect.

Then we find the MLE for \gamma:

$$
\hat{\theta}_d \sim Normal(\beta_X + \gamma G_d, \sigma_d^2)
$$

Let us denote $1/\sigma_d^2$ as $W_d$, the objective function to optimize is:

$$
\sum_d^D{W_d(\hat{\theta}_d - \beta_X - \gamma G)^2}
$$

If we centered the mean of $\hat{\theta}_d$ (weighted by $W$) and suppose $G$ is standardized (mean zero in single cell level, equivalent to $\bar G=0$ in the next section), then $\beta_X=0$. The estimate of $\gamma$ is:

$$
\hat{\gamma} = \dfrac{\sum W_d \theta'_d G_d}{\sum W_d G_d^2}
\\
\theta'_d = \hat \theta_d - \bar \theta
\\
\bar \theta = \dfrac{\sum W_d \hat{\theta_d}}{\sum W_d}
$$

As for the standard error of $\hat \gamma$, we have

$$
var(\hat \gamma) = \dfrac{1}{\sum W_dG_d^2} = \dfrac{var(Y)}{\sum G_i^2 X_i^2}
$$




## Equivalence to the cell level interaction model

Alternative to the two-step model above, we can directly fit an interaction model on single-cell level:

$$
\Delta_i = \beta_x X + \gamma X\cdot G
$$

First of all, the weighted average of $\hat{\theta_d}$ is identical to MLE of $\beta_x$ given that genotype has mean zero. Intuitively, this is correct since

$$
E(\theta) = E(\beta_x+\gamma G) = \beta_x + \gamma E(G)
$$

More formally, we first derive estimator of $\bar \theta$ and $\bar G$ on cell level. Based on inverse variance weighted (IVW) meta-analysis or direct derivation, the weighted average of $\hat{\theta}$ is

$$
\bar \theta = \dfrac{\sum W_d \theta_d}{\sum W_d} = \dfrac{X^T \Delta}{X^T X}
$$

Similarly, the weighted average of $G$ is

$$
\bar G = \dfrac{\sum W_d G}{\sum W_d} = \dfrac{X^T G' X}{X^T X} = \dfrac{\sum G_i X_i^2}{\sum X_i^2}
$$

where $G'$ is a $n\times n$ diagonal matrix with the diagonal elements as the genotypes

Since the log Likelihood for the interaction model is:

$$
\mathcal{L}(\Delta;\beta_x,\gamma) \propto -\sum(\Delta_i-\beta_xX_i-\gamma G_i\cdot X_i)^2
$$

By setting the $\dfrac{d\mathcal{L}(\Delta;\beta_x,\gamma)}{d\beta_x}=0$ to 0, we should find the MLE for $\beta_x$ as:

$$
\hat \beta_x = \dfrac{\sum\Delta_iX_i}{\sum X_i^2} - \gamma \dfrac{\sum G_i X_i^2}{\sum X_i^2} = \bar \theta - \gamma \bar G
$$

Therefore, by setting $\bar G = 0$, the estimator for $\hat \beta_x$ is identical to that of $\bar \theta$. 

Similarly, we can derive the MLE of $\gamma$. Let us denote the interaction term $X\cdot G$ as $X'$ for convenience.

$$
\hat \gamma = \dfrac{X'^T \Delta}{X'^TX'} - \hat \beta \dfrac{X^TX'}{X'^TX'}
$$

Recall that the estimate for $\gamma$ in the two step model is:

$$
\hat \gamma = \dfrac{\sum W_d (\hat \theta_d-\bar \theta) G}{\sum W_d G^2} = \dfrac{X'^T \Delta}{X'^TX'} - \hat \beta \dfrac{X^TX'}{X'^TX'}
$$

Therefore, $\hat \gamma$ is identical in the two approaches.

As for the standard error of $\hat \gamma$, it is obvious that they are the same by plugging in the estimate of $W_d$ in previous equation for $var(\hat \gamma)$.

The advantage of using a two-step model instead of the interaction model is that we decoupled the genetic variation and phenotypic variation with an intermediate "trait" that captures the sufficient statistics for each donor. Hence, when we need to run QTL mapping for the same molecular trait, we only need to repeat the second step on bulk level while retaining the power of single-cell level model. This would bring enormous speed up to the dynamic QTL mapping procedure.

## Simulation





